import { useNavigate } from 'react-router-dom'
import { ChevronLeft } from 'lucide-react'

export default function TermsOfService() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-bg text-text-primary">
      {/* Header */}
      <div className="sticky top-0 z-10 border-b border-border bg-bg/95 backdrop-blur-sm">
        <div className="mx-auto flex max-w-3xl items-center gap-3 px-4 py-3 sm:px-6">
          <button
            onClick={() => navigate(-1)}
            className="btn-icon h-9 w-9 border-transparent bg-transparent"
            aria-label="Go back"
          >
            <ChevronLeft size={20} strokeWidth={1.75} />
          </button>
          <h1 className="text-heading-md font-semibold">Terms of Service</h1>
        </div>
      </div>

      {/* Content */}
      <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6">
        <p className="mb-6 text-caption text-text-tertiary">
          Last updated: June 2025
        </p>

        <div className="space-y-8 text-body text-text-secondary leading-relaxed">
          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using NRVS, you agree to be bound by these Terms of Service
              and all applicable laws and regulations. If you do not agree with any part
              of these terms, you may not use our services.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              2. Description of Service
            </h2>
            <p>
              NRVS is an AI assistant platform that provides conversational AI, website
              generation, task planning (Flow State Mode), and related features. We
              reserve the right to modify, suspend, or discontinue any part of the
              service at any time without prior notice.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              3. User Accounts
            </h2>
            <p>
              You are responsible for maintaining the confidentiality of your account
              credentials. You agree to provide accurate information when creating an
              account and to notify us immediately of any unauthorized use. We are not
              liable for any loss or damage arising from unauthorized account access.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              4. Acceptable Use
            </h2>
            <p>You agree not to use NRVS to:</p>
            <ul className="mt-2 list-inside list-disc space-y-1">
              <li>Violate any applicable law, regulation, or third-party rights</li>
              <li>Generate harmful, illegal, or deceptive content</li>
              <li>Impersonate any person or entity</li>
              <li>Attempt to gain unauthorized access to other accounts or systems</li>
              <li>Use the service to train or fine-tune AI models without permission</li>
              <li>Overload or disrupt the service in any way</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              5. API Keys & Third-Party Services
            </h2>
            <p>
              You may connect your own API keys to power NRVS features. You are
              responsible for the security and usage of your own API keys. NRVS does
              not take responsibility for costs incurred through third-party AI or
              service providers. Third-party services (AI providers, Tavily, E2B) are
              governed by their own terms and privacy policies.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              6. Intellectual Property
            </h2>
            <p>
              You retain ownership of content you create using NRVS. By using the
              service, you grant NRVS the right to process your content to provide the
              requested features. Code, designs, or other outputs generated by NRVS
              based on your prompts belong to you, subject to the limitations of the
              underlying AI model providers.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              7. Disclaimer of Warranties
            </h2>
            <p>
              NRVS is provided "as is" and "as available" without warranties of any kind,
              either express or implied. We do not guarantee that the service will be
              uninterrupted, error-free, or free of harmful outputs. AI responses may
              contain inaccuracies — you are responsible for reviewing and validating
              outputs before relying on them.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              8. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, NRVS shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages,
              including but not limited to loss of profits, data, or use, arising from
              your use of the service.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              9. Termination
            </h2>
            <p>
              We may terminate or suspend your access to NRVS immediately, without
              prior notice, for any reason, including breach of these terms. Upon
              termination, your right to use the service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              10. Changes to Terms
            </h2>
            <p>
              We may revise these Terms of Service at any time. Changes will be posted
              on this page with an updated revision date. Continued use of NRVS after
              changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              11. Governing Law
            </h2>
            <p>
              These terms shall be governed by and construed in accordance with the
              laws of the jurisdiction in which NRVS operates, without regard to its
              conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-heading-md font-semibold text-text-primary">
              12. Contact
            </h2>
            <p>
              For questions about these terms, contact us at{' '}
              <a href="mailto:legal@nrvs.ai" className="text-accent-blue hover:underline">
                legal@nrvs.ai
              </a>
              .
            </p>
          </section>
        </div>

        {/* Footer nav */}
        <div className="mt-12 flex flex-wrap gap-4 border-t border-border pt-6 text-body-sm text-text-tertiary">
          <a href="/privacy" className="hover:text-text-secondary hover:underline">
            Privacy Policy
          </a>
          <span>·</span>
          <a href="/cookies" className="hover:text-text-secondary hover:underline">
            Cookie Policy
          </a>
        </div>
      </div>
    </div>
  )
}